"""Add kyc_status to User model

Revision ID: 0cfd7c7d19a7
Revises: 43e639d44646
Create Date: 2024-10-01 04:11:52.491085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfd7c7d19a7'
down_revision = '43e639d44646'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_status', sa.String(), nullable=True))
    op.drop_column('users', 'kyc_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'kyc_status')
    # ### end Alembic commands ###
