"""Add KYC fields to User model

Revision ID: 43e639d44646
Revises: d9f6b05712ab
Create Date: 2024-09-27 15:31:10.556631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e639d44646'
down_revision = 'd9f6b05712ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('id_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_verified')
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'address')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
